name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  allPackages:
    runs-on: macos-14
    env:
      cancelJob: false
      srcModified: false
    strategy:
      fail-fast: false
      matrix:
        pkgInfo: ['mpv|mpv.tar.gz']

    steps:
      - name: Set env variables
        run: |
          pkgName=$(echo "${{ matrix.pkgInfo }}" | cut -d$'|' -f1)
          echo "pkgName=$pkgName" >> $GITHUB_ENV
          pkgApp=$(echo "${{ matrix.pkgInfo }}" | cut -d$'|' -f2)
          echo "pkgApp=$pkgApp" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check modified files
        run: |
          git diff --name-only HEAD HEAD^ | grep -q "${{ env.pkgName }}" || echo "cancelJob=true" >> $GITHUB_ENV
      
      - name: Build package
        if: ${{ env.cancelJob == 'false' }}
        run: |
          bash "${{ env.pkgName }}"/build.sh
          pkgVer=$(< "${{ env.pkgName }}/${{ env.pkgApp }}.version")
          echo "pkgVer=$pkgVer" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        if: ${{ env.cancelJob == 'false' }}
        with:
          name: "${{ env.pkgName }}"
          path: "${{ env.pkgName }}/${{ env.pkgApp }}"
       
      - uses: softprops/action-gh-release@v2
        if: ${{ env.cancelJob == 'false' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "${{ env.pkgName }}-${{ env.pkgVer }}"
          prerelease: false
          files: |
            ./${{ env.pkgName }}/${{ env.pkgApp }}
            ./${{ env.pkgName }}/${{ env.pkgApp }}.sha256sum
